version: '2'

services:
  
    web:
      image: nginx
      ports:
        - 8010:80 # Set the port to access to the site via HTTP
        - 8011:443 # Set the port to access to the site via HTTPS
      volumes:
        - ./code:/var/www/symfony:rw
        - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
      links:
        - php
        - db

    php:
      build: ./docker/php
      working_dir: /var/www/symfony
      ports:
        - 8013:9000
      volumes:
        - ./code:/var/www/symfony:rw
      environment:
        APP_ENV: dev
        APP_SECRET: CHANGETHIS # Change the APP_SECRET
        DATABASE_URL: "mysql://symfony:symfony@db:3306/symfony?serverVersion=5.7"

    db:
      image: mysql
      command: ["--default-authentication-plugin=mysql_native_password"]
      volumes:
        - ./docker/db/data:/var/lib/mysql
      ports:
        - 8014:3306
        - 8015:33060
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony

    adminer:
      image: adminer
      restart: always
      ports:
        - 8012:8080 # Set the port to access to Adminer

    node:
      # image: node
      build: ./docker/node
      volumes:
        - ./code:/var/www/symfony:rw
